export const fpos = [
  {
    id: "fpo-sehore",
    name: "Sehore Krishi Utpadak Sangh",
    location: "Sehore",
    state: "Madhya Pradesh",
    rating: 4.5,
    reviewCount: 218,
    verified: true,
    organic: true,
    govtRegistered: true,
    story:
      "Founded in 2014 by 320 wheat farmers across the Sehore belt, our collective brings the famed Sharbati wheat directly from black-cotton soils to your kitchen — without middlemen.",
    practices:
      "Rain-fed cultivation, zero-residue storage, hand-graded sorting.",
    certifications: ["FSSAI", "India Organic", "APEDA"],
  },
  {
    id: "fpo-vidisha",
    name: "Vidisha Agro Farmers Producer Co.",
    location: "Vidisha",
    state: "Madhya Pradesh",
    rating: 4.2,
    reviewCount: 142,
    verified: true,
    govtRegistered: true,
    story:
      "A 480-member soybean and pulses cooperative working across Vidisha and Raisen districts.",
    practices: "Integrated pest management, solar-dried storage.",
    certifications: ["FSSAI", "APEDA"],
  },
  {
    id: "fpo-indore",
    name: "Indore Organic Farmers Group",
    location: "Indore",
    state: "Madhya Pradesh",
    rating: 4.6,
    reviewCount: 304,
    verified: true,
    organic: true,
    govtRegistered: true,
    story:
      "Certified-organic gram and dal producers serving institutional and retail buyers since 2016.",
    practices: "Certified organic, vermicompost-based soil care.",
    certifications: ["India Organic", "USDA Organic"],
  },
  {
    id: "fpo-nashik",
    name: "Nashik Veg Farmers Collective",
    location: "Nashik",
    state: "Maharashtra",
    rating: 4.0,
    reviewCount: 89,
    verified: true,
    story:
      "A vegetable-first FPO supplying mandis and processors across western India.",
    practices: "Drip irrigation, cold-chain pickup at farm gate.",
    certifications: ["FSSAI"],
  },
  {
    id: "fpo-kolar",
    name: "Kolar Fresh Produce FPO",
    location: "Kolar",
    state: "Karnataka",
    rating: 4.4,
    reviewCount: 176,
    verified: true,
    story:
      "Specialists in vine-ripened tomatoes and leafy greens from the Kolar plateau.",
    practices: "Mulched beds, daily harvest dispatch.",
    certifications: ["FSSAI", "GlobalG.A.P"],
  },
  {
    id: "fpo-bihar",
    name: "Bihar Agro Collective",
    location: "Muzaffarpur",
    state: "Bihar",
    rating: 4.3,
    reviewCount: 121,
    verified: true,
    story:
      "Cold-pressed mustard oil and seasonal produce from the Gangetic plains.",
    practices: "Wood-pressed, single-origin sourcing.",
    certifications: ["FSSAI"],
  },
  {
    id: "fpo-ratnagiri",
    name: "Ratnagiri Women Farmers Group",
    location: "Ratnagiri",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 98,
    verified: true,
    story:
      "An all-women collective producing handmade pickles and Alphonso preserves.",
    practices: "Sun-cured, small-batch, family recipes.",
    certifications: ["FSSAI"],
  },
  {
    id: "fpo-erode",
    name: "Erode Spice Farmers Collective",
    location: "Erode",
    state: "Tamil Nadu",
    rating: 4.4,
    reviewCount: 154,
    verified: true,
    organic: true,
    story:
      "Turmeric and chilli growers from the Erode region — the turmeric capital of India.",
    practices: "Boiled-and-dried traditional curing, stone-milled.",
    certifications: ["India Organic", "FSSAI"],
  },
];

export const bulkProducts = [
  {
    id: "b1",
    type: "bulk",
    name: "Wheat – Sharbati",
    category: "Grains",
    grade: "A",
    location: "Sehore",
    state: "Madhya Pradesh",
    distanceKm: 42,
    fpoId: "fpo-sehore",
    quantityKg: 1200,
    harvestDaysAgo: 2,
    priceMin: 28,
    priceMax: 30,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=70",
  },
  {
    id: "b2",
    type: "bulk",
    name: "Soybean",
    category: "Pulses",
    grade: "B",
    location: "Vidisha",
    state: "Madhya Pradesh",
    distanceKm: 88,
    fpoId: "fpo-vidisha",
    quantityKg: 800,
    harvestDaysAgo: 5,
    priceMin: 52,
    priceMax: 55,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1599909533730-9c2b21c61f12?w=800&q=70",
  },
  {
    id: "b3",
    type: "bulk",
    name: "Chana (Gram)",
    category: "Pulses",
    grade: "A",
    location: "Indore",
    state: "Madhya Pradesh",
    distanceKm: 64,
    fpoId: "fpo-indore",
    quantityKg: 500,
    harvestDaysAgo: 1,
    priceMin: 60,
    priceMax: 65,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=70",
  },
  {
    id: "b4",
    type: "bulk",
    name: "Onion",
    category: "Vegetables",
    grade: "C",
    location: "Nashik",
    state: "Maharashtra",
    distanceKm: 220,
    fpoId: "fpo-nashik",
    quantityKg: 2000,
    harvestDaysAgo: 10,
    priceMin: 12,
    priceMax: 15,
    delivery: false,
    image:
      "https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=800&q=70",
  },
  {
    id: "b5",
    type: "bulk",
    name: "Tomato",
    category: "Vegetables",
    grade: "A",
    location: "Kolar",
    state: "Karnataka",
    distanceKm: 310,
    fpoId: "fpo-kolar",
    quantityKg: 300,
    harvestDaysAgo: 0,
    priceMin: 18,
    priceMax: 22,
    delivery: false,
    image:
      "https://images.unsplash.com/photo-1546470427-e26264be0b0d?w=800&q=70",
  },
];

export const retailProducts = [
  {
    id: "r1",
    type: "retail",
    name: "Organic Wheat Atta – 5kg",
    category: "Staples",
    productType: "Organic",
    fpoId: "fpo-sehore",
    price: 280,
    rating: 4.5,
    reviewCount: 312,
    stock: 24,
    image:
      "https://images.unsplash.com/photo-1568718247028-cba1cf4b4cdf?w=800&q=70",
    description:
      "Stone-ground Sharbati wheat atta with naturally high protein and a soft, sweet flavour.",
    ingredients: "100% whole Sharbati wheat",
    certifications: ["India Organic", "FSSAI"],
    shelfLife: "6 months from packaging",
  },
  {
    id: "r2",
    type: "retail",
    name: "Mustard Oil – 1L",
    category: "Oils",
    productType: "Natural",
    fpoId: "fpo-bihar",
    price: 220,
    rating: 4.3,
    reviewCount: 198,
    stock: 40,
    image:
      "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=800&q=70",
    description:
      "Wood-pressed (kachi ghani) mustard oil, single-origin from Muzaffarpur.",
    ingredients: "100% mustard seeds",
    certifications: ["FSSAI"],
    shelfLife: "9 months",
  },
  {
    id: "r3",
    type: "retail",
    name: "Chana Dal – 1kg",
    category: "Pulses",
    productType: "Regular",
    fpoId: "fpo-indore",
    price: 95,
    rating: 4.2,
    reviewCount: 87,
    stock: 60,
    image:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=70",
    description:
      "Sun-dried, hand-cleaned split Bengal gram from Indore region farms.",
    ingredients: "100% chana dal",
    certifications: ["FSSAI"],
    shelfLife: "12 months",
  },
  {
    id: "r4",
    type: "retail",
    name: "Mango Pickle – 500g",
    category: "Pickles",
    productType: "Handmade",
    fpoId: "fpo-ratnagiri",
    price: 180,
    rating: 4.6,
    reviewCount: 142,
    stock: 18,
    image:
      "https://images.unsplash.com/photo-1599909533730-9c2b21c61f12?w=800&q=70",
    description:
      "Sun-cured raw mango pickle in cold-pressed mustard oil — a Konkan family recipe.",
    ingredients:
      "Raw mango, mustard oil, salt, fenugreek, mustard seeds, asafoetida, chilli",
    certifications: ["FSSAI"],
    shelfLife: "12 months",
  },
  {
    id: "r5",
    type: "retail",
    name: "Turmeric Powder – 250g",
    category: "Spices",
    productType: "Organic",
    fpoId: "fpo-erode",
    price: 70,
    rating: 4.4,
    reviewCount: 256,
    stock: 80,
    image:
      "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=70",
    description: "Stone-milled Erode turmeric, naturally high in curcumin.",
    ingredients: "100% turmeric (Curcuma longa)",
    certifications: ["India Organic", "FSSAI"],
    shelfLife: "18 months",
  },
];

export const reviews = [
  {
    id: "rv1",
    author: "Anita S.",
    rating: 5,
    text: "Atta is incredibly fresh — rotis stay soft for hours. You can taste the difference.",
    category: "Product Quality",
  },
  {
    id: "rv2",
    author: "Rahul M.",
    rating: 4,
    text: "Delivered in 3 days, well-sealed. Will reorder.",
    category: "Delivery Experience",
  },
  {
    id: "rv3",
    author: "Procurement, Annapurna Foods",
    rating: 5,
    text: "Worked with the FPO team for a 2-tonne order. Clear communication, fair pricing.",
    category: "Communication",
  },
];

export const fpoById = (id) => fpos.find((f) => f.id === id);
